"""NEW

Revision ID: 1ba39a35ac50
Revises: beb5d5398837
Create Date: 2024-04-15 23:13:01.948903

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1ba39a35ac50'
down_revision = 'beb5d5398837'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tasks', sa.Column('user_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'Tasks', 'Users', ['user_id'], ['id'])
    op.drop_column('Users', 'task')
    op.drop_column('Users', 'task_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('task_status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('Users', sa.Column('task', mysql.JSON(), nullable=True))
    op.drop_constraint(None, 'Tasks', type_='foreignkey')
    op.drop_column('Tasks', 'user_id')
    # ### end Alembic commands ###
