"""NEW

Revision ID: 450fe5e0ab5d
Revises: 1ba39a35ac50
Create Date: 2024-04-16 03:18:29.051899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '450fe5e0ab5d'
down_revision = '1ba39a35ac50'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Stat',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('video_note_time', sa.Integer(), nullable=True),
    sa.Column('is_music', sa.Boolean(), nullable=True),
    sa.Column('is_texture', sa.Boolean(), nullable=True),
    sa.Column('time_for_done', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Stat')
    # ### end Alembic commands ###
