"""NEW

Revision ID: f1cfdc69a4d4
Revises: 450fe5e0ab5d
Create Date: 2024-04-16 03:19:04.930761

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f1cfdc69a4d4'
down_revision = '450fe5e0ab5d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Stat', 'time_for_done',
               existing_type=mysql.DATETIME(),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Stat', 'time_for_done',
               existing_type=sa.Integer(),
               type_=mysql.DATETIME(),
               existing_nullable=False)
    # ### end Alembic commands ###
